const AMADEUSINSPIRATIONORIGINCODES = ["FRA","MUC","BOG","AJU","BEL","BHZ","BPS","BSB","CGB","CGR","CWB","FLN","FOR","GYN","IGU","JPA","LDB","MAO","MCP","MCZ","MGF","NAT","NVT","PMW","POA","PVH","REC","RIO","SAO","SJP","SLZ","SSA","THE","UDI","VIX","BHI","BRC","BUE","COR","CRD","EQS","IGR","LUQ","MDQ","MDZ","NQN","ROS","SLA","TUC","SYD","LON","MAD","NCE","PAR","ANF","SCL","SJU","ABQ","ALB","ANC","ATL","AUS","HFD","BHM","BNA","BOI","BOS","BTV","BUF","BUR","WAS","CAK","CHI","CHS","CLE","CLT","CMH","COS","CVG","DAY","DEN","DFW","DSM","DTT","ELP","NYC","FLL","FMY","GEG","GRR","GSO","GSP","HNL","HOU","HPN","IND","JAX","LAS","LAX","LGB","MKC","ORL","MEM","MHT","MIA","MKE","MSP","MSY","OAK","OKC","OMA","ONT","ORF","PBI","PDX","PHL","PHX","PIT","PVD","RDU","RIC","RNO","ROC","SAC","SAN","SAT","SAV","SDF","SEA","SFO","SJC","SLC","SNA","STL","SYR","TPA","TUL","TUS","TYS","YCD","YEA","YFC","YHZ","YKF","YLW","YMM","YMQ","YOW","YQB","YQG","YQM","YQR","YQT","YQU","YSJ","YTO","YVO","YVR","YWG","YWK","YXE","YXJ","YXS","YXU","YXX","YYC","YYG","YYJ","YYT","AAQ","AER","ARH","ASF","EGO","GOJ","KGD","KRR","KUF","KZN","LED","MCX","MMK","MOW","MRV","NBC","OGZ","PEE","PEZ","REN","ROV","SCW","STW","UFA","USK","VOG","VOZ","TYO","BJS","SHA","CAN","HKG","HGH","BLR","BOM","CCJ","CCU","DEL","TLV","BKK","CNX","HKT","CUN","MEX","SJD","PVR","GDL","SIN","AMS","DXB","OSA","PRG","SVX","SEL","CJU","PUS"];


Object.freeze(AMADEUSINSPIRATIONORIGINCODES);
Object.freeze(this)


module.exports = AMADEUSINSPIRATIONORIGINCODES;
